# Generated by Django 5.2 on 2025-04-03 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity_app', '0002_mymodel_settings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
